<?php
    $title = 'Add new bill';
    $this->headTitle($title);
?>
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Add Bill Form
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-6">
                        <?php
                            $form = $this->form;
                            $form->prepare();
                        ?>
                        <?php echo $this->form()->openTag($form); ?>
                        <div class="form-group">
                            <?php echo $this->formHidden($form->get('id')); ?>
                        </div>
                        <div class="form-group">
                            <?php echo $this->formRow($form->get('creditor'), null, null, 'partials/vertical-form'); ?>
                        </div>
                        <div class="form-group">
                            <?php echo $this->formRow($form->get('creditor_url'), null, null, 'partials/vertical-form'); ?>
                        </div>
                        <div class="form-group">
                            <?php echo $this->formRow($form->get('debt_type'), null, null, 'partials/vertical-form'); ?>
                        </div>
                        <div class="form-group">
                            <?php echo $this->formRow($form->get('type'), null, null, 'partials/vertical-form'); ?>
                        </div>
                        <div class="form-group">
                            <?php echo $this->formRow($form->get('monthly_payment'), null, null, 'partials/vertical-form'); ?>
                        </div>
                        <div class="form-group">
                            <?php echo $this->formRow($form->get('due_date'), null, null, 'partials/vertical-form'); ?>
                        </div>
                        <div class="form-group">
                            <?php echo $this->formRow($form->get('balance'), null, null, 'partials/vertical-form'); ?>
                        </div>
                        <div class="form-group">
                            <?php echo $this->formInput($form->get('submit')); ?>
                        </div>
                        <?php echo $this->form()->closeTag($form); ?>
                    </div>
                    <!-- /.col-lg-6 (nested) -->
                </div>
                <!-- /.row (nested) -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>




