<?php
$title = 'Add new payment';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('bill', array('action' => 'payment'), null, true));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('bill_id'));
echo $this->formRow($form->get('amount'));
echo $this->formInput($form->get('submit'));
echo $this->form()->closeTag($form);

