<?php // http://stackoverflow.com/a/14891852/1004027 ?>
<ul class="nav navbar-nav">
    <?php $count = 0 ?>
    <?php foreach ($this->container as $page): ?>
        <?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
        <?php // when using partials we need to manually check for ACL conditions ?>
        <?php if( ! $page->isVisible() || !$this->navigation()->accept($page)) continue; ?>
        <?php $hasChildren = $page->hasPages(true) ?>
        <?php if( ! $hasChildren): ?>
            <li <?php if($page->isActive()) echo 'class="active"'?>>
                <a class="nav-header" href="<?php echo $page->getHref() ?>">
                    <?php echo $this->translate($page->getLabel()) ?>
                </a>
            </li>
        <?php else: ?>
            <li <?php if($page->isActive(true)) echo 'class="active"'?>>
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <span><?php echo $this->translate($page->getLabel()) ?></span>
                    <span class="caret"></span>
                </a>

                <ul class="dropdown-menu" id="page_<?php echo $count ?>">
                    <?php foreach($page->getPages() as $child): ?>
                        <?php // when using partials we need to manually check for ACL conditions ?>
                        <?php if( ! $child->isVisible() || !$this->navigation()->accept($child)) continue; ?>
                        <li <?php if($child->isActive(true)) echo 'class="active"'?>>
                            <a href="<?php echo $child->getHref() ?>">
                                <?php echo $this->translate($child->getLabel()) ?>
                            </a>
                        </li>
                    <?php endforeach ?>
                </ul>
            </li>
        <?php endif ?>
        <?php $count++ ?>
    <?php endforeach ?>

    <?php if(!empty($this->layout()->currentUser)):?>
        <?php
        $user = $this->layout()->currentUser;
        if(!empty($user->user))
        {
            $user = $user->user;
        }
        ?>
        <li class="user-nav">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <span class="glyphicon glyphicon-user"></span>
                <span><?= $user->firstName?></span>
                <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
                <li>
                    <a href="<?= $this->url('Application\account', array('action' => 'logout'))?>">Logout</a>
                </li>
            </ul>
        </li>
    <?php endif; ?>

</ul>