<?php // setting links in a view script:
    $this->headLink()->appendStylesheet($this->basePath() . '/css/login.css')
?>
<?php // rendering the links: ?>
<?php echo $this->headLink() ?>
<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Please Sign In</h3>
                </div>
                <div class="panel-body">
                    <?php
                    $form->prepare();
                    $form->setAttribute('class', 'form-horizontal');
                    $form->setAttribute('action', $this->url('Application\account', array('action' => 'login')));
                    ?>
                    <?= $this->form()->openTag($form);
                    ?>
                    <fieldset>
                        <div class="form-group">
                            <?= $this->formElement($form->get("username")) ?>
                        </div>
                        <div class="form-group">
                            <?= $this->formElement($form->get("password")) ?>
                        </div>
                        <div class="checkbox">
                            <label>
                                <?= $this->formElement($form->get("rememberme")) ?>Remember Me
                            </label>
                        </div>
                        <button class="btn btn-lg btn-success btn-block" name="submit" type="submit">Submit</button>
                        <a class="small" href="<?= $this->url('Application\account', array('action' => 'forgot-password'))?>">Forgot Password? Click Here</a>
                    </fieldset>
                    <?= $this->form()->closeTag();?>
                </div>
            </div>
        </div>
    </div>
</div>