<?php echo $this->doctype(); ?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
            ->appendStylesheet($this->basePath() . '/css/bootstrap.min.css')
            ->appendStylesheet($this->basePath() . '/css/plugins/metisMenu/metisMenu.min.css')
            ->appendStylesheet($this->basePath() . '/css/plugins/timeline.css')
            ->appendStylesheet($this->basePath() . '/css/sb-admin-2.css')
            ->appendStylesheet($this->basePath() . '/css/plugins/morris.css')
            ->appendStylesheet($this->basePath() . '/font-awesome-4.1.0/css/font-awesome.min.css')
    ?>
  </head>

  <body>

  <div id="wrapper">

  <!-- Navigation -->
  <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <?php
        if (isset($currentUser)) {
            echo $this->partial('layout/navigation');
            echo $this->partial('layout/sidebar');
        }
    ?>
  </nav>

  <div id="page-wrapper">

      <div class="container">
          <div class="row">
              <div class="col-xs-12 flash-messages">
                  <?php echo $this->partial('layout/flash'); ?>
              </div>
          </div>
      </div>

  <?php echo $this->content; ?>

  </div>
  <!-- /#page-wrapper -->

  <!-- Scripts -->
  <?php echo $this->headScript()->appendFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
      ->appendFile($this->basePath() . '/js/jquery.min.js')
      ->appendFile($this->basePath() . '/js/bootstrap.min.js')
      ->appendFile($this->basePath() . '/js/plugins/metisMenu/metisMenu.min.js')
      ->appendFile($this->basePath() . '/js/plugins/morris/raphael.min.js')
      ->appendFile($this->basePath() . '/js/plugins/morris/morris.min.js')
      ->appendFile($this->basePath() . '/js/plugins/morris/morris-data.js')
      ->appendFile($this->basePath() . '/js/sb-admin-2.js')

      ?>
  </body>
</html>
