<?php
    $title = 'Edit bill';
    $this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('bill', array('action' => 'edit','id'=>$this->id,)));
    $form->prepare();
?>

<?php echo $this->form()->openTag($form); ?>
<div class="form-group">
    <?php echo $this->formHidden($form->get('id')); ?>
</div>

<div class="form-group">
    <?php echo $this->formRow($form->get('creditor')); ?>
</div>
<div class="form-group">
    <?php echo $this->formRow($form->get('creditor_url')); ?>
</div>
<div class="form-group">
    <?php echo $this->formRow($form->get('type')); ?>
</div>
<div class="form-group">
    <?php echo $this->formRow($form->get('m_payment')); ?>
</div>
<div class="form-group">
    <?php echo $this->formRow($form->get('balance')); ?>
</div>

<div class="form-group">
    <?php echo $this->formInput($form->get('submit')); ?>
</div>
<?php echo $this->form()->closeTag($form); ?>


