<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Dashboard</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-bar-chart-o fa-fw"></i> Bill List
                <div class="pull-right">
                    <div class="btn-group">
                        <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                            Actions
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu pull-right" role="menu">
                            <li><a href="<?php echo $this->url('bill', array('action'=>'add'));?>">Add new bill</a></li>
                            <li><a href="#">Another action</a>
                            </li>
                            <li><a href="#">Something else here</a>
                            </li>
                            <li class="divider"></li>
                            <li><a href="#">Separated link</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="table-responsive">
                            <table class="table table-bordered table-hover table-striped">
                                <thead>
                                <thead>
                                    <tr>
                                        <th>Creditor</th>
                                        <th>Type</th>
                                        <th>Monthly Payment</th>
                                        <th>Last Payment</th>
                                        <th>Balance</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                </thead>
                                <tbody>
                                <?php foreach($bills as $bill) :
                                    $latest_payment = (is_object($bill->get_latest_payment())) ? $bill->get_latest_payment()->date->format('m/d/Y') : "No Payment Recorded";
                                    $running_balance = (is_object($bill->get_latest_payment())) ? $bill->get_latest_payment()->running_balance : $bill->balance;
                                    ?>
                                    <tr>
                                        <td><a target="_blank" href="<?php echo $bill->creditor_url; ?>"><?php echo $bill->creditor;?></a></td>
                                        <td><?php echo $bill->type;?></td>
                                        <td><?php echo "$".$bill->m_payment; ?></td>
                                        <td class="<?php echo $bill->get_latest_payment_class(); ?>"><?php echo $latest_payment; ?></td>
                                        <td><?php echo $running_balance; ?></td>
                                        <td>
                                            <div class="dropdown">
                                                <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
                                                    Action
                                                    <span class="caret"></span>
                                                </button>
                                                <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                                                    <li role="presentation"><a role="menuitem" tabindex="-1" href="<?php echo $this->url('bill',array('action'=>'edit', 'id' => $bill->id));?>">Edit</a></li>
                                                    <li role="presentation"><a role="menuitem" tabindex="-1" href="<?php echo $this->url('bill',array('action'=>'delete', 'id' => $bill->id));?>">Delete</a></li>
                                                    <li role="presentation"><a role="menuitem" tabindex="-1" href="<?php echo $this->url('bill' ,array('action'=>'payment', 'id' => $bill->id));?>">Payment</a></li>
                                                    <li role="presentation"><a role="menuitem" tabindex="-1" href="<?php echo $this->url('bill' ,array('action'=>'payment-history', 'id' => $bill->id));?>">Payment History</a></li>
                                                </ul>
                                            </div>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                        <!-- /.table-responsive -->
                    </div>
                    <!-- /.col-lg-4 (nested) -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-bar-chart-o fa-fw"></i> Balance Chart
                <div class="pull-right">
                    <div class="btn-group">
                        <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                            Actions
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu pull-right" role="menu">
                            <li><a href="#">Action</a>
                            </li>
                            <li><a href="#">Another action</a>
                            </li>
                            <li><a href="#">Something else here</a>
                            </li>
                            <li class="divider"></li>
                            <li><a href="#">Separated link</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div id="morris-area-chart"></div>
            </div>
        <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    <!-- /.panel -->
    </div>
    <!-- /.col-lg-9 -->
    <div class="col-lg-3">
        <!-- /.panel -->
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-bar-chart-o fa-fw"></i> Donut Chart Example
            </div>
            <div class="panel-body">
                <div id="morris-donut-chart"></div>
                <a href="#" class="btn btn-default btn-block">View Details</a>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-3-->
</div>
<!-- /.row -->


