<div class="navbar-default" role="navigation">
    <div class="sidebar-nav">
        <ul class="nav" id="side-menu">
            <li>
                <a class="active" href="<?php echo $this->url('budget-home'); ?>"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
            </li>
            <li>
                <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Bills<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <?php
                        foreach($this->plugin('billtracker')->ListBills() as $bill) {
                            $route = $this->url('bill', array('action'=>'payment-history', 'id' => $bill['id']));
                            echo '<li><a href="' . $route . '">' . $bill['creditor'] . '</a></li>';
                            unset($route);
                        }
                    ?>
                </ul>
                <!-- /.nav-second-level -->
            </li>
        </ul>
    </div>
    <!-- /.sidebar-collapse -->
</div>
<!-- /.navbar-static-side -->