<?php $form = $this->form; ?>
<?php $form->prepare(); ?>
<?php echo $this->form()->openTag($form); ?>
    <div class="form-group">
        <?php echo $this->formHidden($form->get('id')); ?>
    </div>
    <div class="form-group">
        <?php echo $this->formRow($form->get('bill_id'), null, null, 'partials/vertical-form'); ?>
    </div>
    <div class="form-group">
        <?php echo $this->formRow($form->get('amount'), null, null, 'partials/vertical-form'); ?>
    </div>
    <div class="form-group">
        <?php echo $this->formInput($form->get('submit')); ?>
    </div>
<?php echo $this->form()->closeTag($form); ?>